import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";

import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { TanstackProvider } from "@/lib/components/providers/TanstackProvider";

const _geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const _geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`debug-screens antialiased`}>
          <Toaster position="top-right" richColors />
          <header className="flex h-16 items-center justify-end gap-4 p-4"></header>
          <TanstackProvider>{children}</TanstackProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
